//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KebabGGbab.Json.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KebabGGbab.Json.Resources.ValidationStrings", typeof(ValidationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для чтения файла FileAccess должен быть &apos;Read&apos; или &apos;ReadWrite&apos;. Текущее значение &apos;{0}&apos;..
        /// </summary>
        internal static string OptionReadIncorrectFileAccessFormat {
            get {
                return ResourceManager.GetString("OptionReadIncorrectFileAccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для чтения файла FileMode должен быть &apos;Open&apos; или &apos;OpenOrCreate&apos;. Текущее значение &apos;{0}&apos;..
        /// </summary>
        internal static string OptionReadIncorrectFileModeFormat {
            get {
                return ResourceManager.GetString("OptionReadIncorrectFileModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для записи в файл FileAccess должен быть &apos;Write&apos; или &apos;ReadWrite&apos;. Текущее значение &apos;{0}&apos;..
        /// </summary>
        internal static string OptionWriteIncorrectFileAccessFormat {
            get {
                return ResourceManager.GetString("OptionWriteIncorrectFileAccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для записи в файл FileMode должен быть &apos;Create&apos;, &apos;CreateNew&apos;, &apos;OpenOrCreate&apos;, &apos;Truncate&apos; или &apos;Append&apos;. Текущее значение &apos;{0}&apos;..
        /// </summary>
        internal static string OptionWriteIncorrectFileModeFormat {
            get {
                return ResourceManager.GetString("OptionWriteIncorrectFileModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток должен быть открыт для чтения..
        /// </summary>
        internal static string StreamNotOpenRead {
            get {
                return ResourceManager.GetString("StreamNotOpenRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток должен быть открыт для записи..
        /// </summary>
        internal static string StreamNotOpenWrite {
            get {
                return ResourceManager.GetString("StreamNotOpenWrite", resourceCulture);
            }
        }
    }
}
